version: "3.8"

services:
  elis-nextjs-app:
    build: .
    container_name: elis-nextjs-app
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production
      AUTH_SERVICE: "https://elis.rubencipriano.top/api/auth-service"
      LOCATION_SERVICE: "https://elis.rubencipriano.top/api/location-service"
    networks:
      - nginx_backend
    restart: always

networks:
  nginx_backend:
    external: true