// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TimeFlow.Data;

#nullable disable

namespace TimeFlow.Data.Migrations
{
    [DbContext(typeof(TimeFlowDbContext))]
    [Migration("20260531164604_AddMemberCompensationCadence")]
    partial class AddMemberCompensationCadence
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TimeFlow.Data.Models.AuditLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("action");

                    b.Property<Guid?>("ActorId")
                        .HasColumnType("uuid")
                        .HasColumnName("actor_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("OrgId")
                        .HasColumnType("uuid")
                        .HasColumnName("org_id");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("payload");

                    b.Property<string>("TargetId")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("target_id");

                    b.Property<string>("TargetType")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("target_type");

                    b.HasKey("Id");

                    b.HasIndex("ActorId")
                        .HasDatabaseName("ix_audit_log_actor");

                    b.HasIndex("OrgId", "CreatedAt")
                        .HasDatabaseName("ix_audit_log_org_created");

                    b.ToTable("audit_log", (string)null);
                });

            modelBuilder.Entity("TimeFlow.Data.Models.HourType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Billable")
                        .HasColumnType("boolean")
                        .HasColumnName("billable");

                    b.Property<string>("Color")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("color");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("name");

                    b.Property<Guid>("OrgId")
                        .HasColumnType("uuid")
                        .HasColumnName("org_id");

                    b.HasKey("Id");

                    b.HasIndex("OrgId", "Name")
                        .IsUnique()
                        .HasDatabaseName("ix_hour_types_org_name_unique");

                    b.ToTable("hour_types", (string)null);
                });

            modelBuilder.Entity("TimeFlow.Data.Models.IntegrationConnection", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<string>("EncryptedCredentials")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("encrypted_credentials");

                    b.Property<DateTime?>("LastVerifiedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_verified_at");

                    b.Property<string>("LastVerifyError")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("last_verify_error");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("name");

                    b.Property<Guid>("OrgId")
                        .HasColumnType("uuid")
                        .HasColumnName("org_id");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("project_id");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("provider");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpstreamUserId")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("upstream_user_id");

                    b.Property<string>("UpstreamUserName")
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("upstream_user_name");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("UserId");

                    b.HasIndex("OrgId", "Provider", "Name")
                        .IsUnique()
                        .HasDatabaseName("ix_integration_connections_org_provider_name_unique");

                    b.HasIndex("ProjectId", "UserId", "Provider")
                        .IsUnique()
                        .HasDatabaseName("ix_integration_connections_project_user_provider_unique");

                    b.ToTable("integration_connections", (string)null);
                });

            modelBuilder.Entity("TimeFlow.Data.Models.IntegrationSyncJob", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("CancelRequested")
                        .HasColumnType("boolean")
                        .HasColumnName("cancel_requested");

                    b.Property<Guid>("ConnectionId")
                        .HasColumnType("uuid")
                        .HasColumnName("connection_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("ErrorCode")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("error_code");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("text")
                        .HasColumnName("error_message");

                    b.Property<DateTime?>("FinishedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("finished_at");

                    b.Property<bool>("FullResync")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("full_resync");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("kind");

                    b.Property<Guid>("OrgId")
                        .HasColumnType("uuid")
                        .HasColumnName("org_id");

                    b.Property<int>("ProgressDone")
                        .HasColumnType("integer")
                        .HasColumnName("progress_done");

                    b.Property<int>("ProgressTotal")
                        .HasColumnType("integer")
                        .HasColumnName("progress_total");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<Guid?>("StartedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("started_by");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<string>("SummaryJson")
                        .HasColumnType("text")
                        .HasColumnName("summary");

                    b.HasKey("Id");

                    b.HasIndex("StartedBy");

                    b.HasIndex("ConnectionId", "CreatedAt")
                        .HasDatabaseName("ix_sync_jobs_connection_created");

                    b.HasIndex("OrgId", "Status")
                        .HasDatabaseName("ix_sync_jobs_org_status");

                    b.ToTable("integration_sync_jobs", (string)null);
                });

            modelBuilder.Entity("TimeFlow.Data.Models.Invoice", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("BilledPartyName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("billed_party_name");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("currency");

                    b.Property<DateOnly?>("DueAt")
                        .HasColumnType("date")
                        .HasColumnName("due_at");

                    b.Property<DateTime?>("IssuedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("issued_at");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("number");

                    b.Property<Guid>("OrgId")
                        .HasColumnType("uuid")
                        .HasColumnName("org_id");

                    b.Property<DateTime?>("PaidAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("paid_at");

                    b.Property<DateOnly>("PeriodFrom")
                        .HasColumnType("date")
                        .HasColumnName("period_from");

                    b.Property<DateOnly>("PeriodTo")
                        .HasColumnType("date")
                        .HasColumnName("period_to");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("project_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<decimal>("Subtotal")
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("subtotal");

                    b.Property<decimal>("TaxAmount")
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("tax_amount");

                    b.Property<decimal>("TaxPct")
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("tax_pct");

                    b.Property<decimal>("Total")
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("total");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("ProjectId");

                    b.HasIndex("OrgId", "Number")
                        .IsUnique()
                        .HasDatabaseName("ix_invoices_org_number_unique");

                    b.HasIndex("OrgId", "ProjectId")
                        .HasDatabaseName("ix_invoices_org_project");

                    b.HasIndex("OrgId", "Status")
                        .HasDatabaseName("ix_invoices_org_status");

                    b.ToTable("invoices", (string)null);
                });

            modelBuilder.Entity("TimeFlow.Data.Models.InvoiceLine", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("amount");

                    b.Property<decimal>("BillRate")
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("bill_rate");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("character varying(400)")
                        .HasColumnName("description");

                    b.Property<decimal>("Hours")
                        .HasColumnType("numeric(6,2)")
                        .HasColumnName("hours");

                    b.Property<Guid>("InvoiceId")
                        .HasColumnType("uuid")
                        .HasColumnName("invoice_id");

                    b.Property<int>("Ordinal")
                        .HasColumnType("integer")
                        .HasColumnName("ordinal");

                    b.Property<Guid?>("WorklogId")
                        .HasColumnType("uuid")
                        .HasColumnName("worklog_id");

                    b.HasKey("Id");

                    b.HasIndex("WorklogId");

                    b.HasIndex("InvoiceId", "Ordinal")
                        .HasDatabaseName("ix_invoice_lines_invoice_ordinal");

                    b.ToTable("invoice_lines", (string)null);
                });

            modelBuilder.Entity("TimeFlow.Data.Models.LeaveType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Color")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("color");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<decimal?>("DefaultHours")
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("default_hours");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("name");

                    b.Property<Guid>("OrgId")
                        .HasColumnType("uuid")
                        .HasColumnName("org_id");

                    b.Property<bool>("Paid")
                        .HasColumnType("boolean")
                        .HasColumnName("paid");

                    b.HasKey("Id");

                    b.HasIndex("OrgId", "Name")
                        .IsUnique()
                        .HasDatabaseName("ix_leave_types_org_name_unique");

                    b.ToTable("leave_types", (string)null);
                });

            modelBuilder.Entity("TimeFlow.Data.Models.NativeProject", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Address")
                        .HasColumnType("text")
                        .HasColumnName("address");

                    b.Property<bool>("Archived")
                        .HasColumnType("boolean")
                        .HasColumnName("archived");

                    b.Property<decimal?>("BillRate")
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("bill_rate");

                    b.Property<string>("Code")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("code");

                    b.Property<Guid?>("ConnectionId")
                        .HasColumnType("uuid")
                        .HasColumnName("connection_id");

                    b.Property<string>("ContactEmail")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("contact_email");

                    b.Property<string>("ContactName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("contact_name");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<decimal?>("DefaultBillRate")
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("default_bill_rate");

                    b.Property<string>("HolidayCountry")
                        .HasMaxLength(2)
                        .HasColumnType("varchar(2)")
                        .HasColumnName("holiday_country");

                    b.Property<string>("HolidayProfile")
                        .HasColumnType("text")
                        .HasColumnName("holiday_profile");

                    b.Property<DateTime?>("LastSyncedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_synced_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("name");

                    b.Property<Guid>("OrgId")
                        .HasColumnType("uuid")
                        .HasColumnName("org_id");

                    b.Property<Guid?>("ParentProjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("parent_project_id");

                    b.Property<string>("ScheduleConfig")
                        .HasColumnType("text")
                        .HasColumnName("schedule_config");

                    b.Property<string>("TaxId")
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("tax_id");

                    b.Property<string>("Type")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasDefaultValue("project")
                        .HasColumnName("type");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpstreamProjectId")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("upstream_project_id");

                    b.Property<string>("UpstreamRawJson")
                        .HasColumnType("text")
                        .HasColumnName("upstream_raw_json");

                    b.Property<DateTime?>("UpstreamUpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("upstream_updated_at");

                    b.HasKey("Id");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("OrgId")
                        .HasDatabaseName("ix_native_projects_org");

                    b.HasIndex("ParentProjectId");

                    b.HasIndex("ConnectionId", "UpstreamProjectId")
                        .IsUnique()
                        .HasDatabaseName("ix_native_projects_connection_upstream_unique")
                        .HasFilter("connection_id IS NOT NULL");

                    b.HasIndex("OrgId", "Code")
                        .IsUnique()
                        .HasDatabaseName("ix_native_projects_org_code_unique");

                    b.HasIndex("OrgId", "ParentProjectId")
                        .HasDatabaseName("ix_native_projects_org_parent");

                    b.ToTable("native_projects", (string)null);
                });

            modelBuilder.Entity("TimeFlow.Data.Models.NativeTask", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("AssigneeId")
                        .HasColumnType("uuid")
                        .HasColumnName("assignee_id");

                    b.Property<string>("AssigneeUpstreamId")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("assignee_upstream_id");

                    b.Property<Guid?>("ConnectionId")
                        .HasColumnType("uuid")
                        .HasColumnName("connection_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<Guid>("OrgId")
                        .HasColumnType("uuid")
                        .HasColumnName("org_id");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("project_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("status");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("title");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpstreamRawJson")
                        .HasColumnType("text")
                        .HasColumnName("upstream_raw_json");

                    b.Property<string>("UpstreamTaskId")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("upstream_task_id");

                    b.Property<DateTime?>("UpstreamUpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("upstream_updated_at");

                    b.Property<string>("UpstreamVersionId")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("upstream_version_id");

                    b.Property<string>("UpstreamVersionName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("upstream_version_name");

                    b.HasKey("Id");

                    b.HasIndex("AssigneeId");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("ProjectId")
                        .HasDatabaseName("ix_native_tasks_project");

                    b.HasIndex("ConnectionId", "UpstreamTaskId")
                        .IsUnique()
                        .HasDatabaseName("ix_native_tasks_connection_upstream_unique")
                        .HasFilter("connection_id IS NOT NULL");

                    b.HasIndex("OrgId", "Status")
                        .HasDatabaseName("ix_native_tasks_org_status");

                    b.ToTable("native_tasks", (string)null);
                });

            modelBuilder.Entity("TimeFlow.Data.Models.OrgMembership", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<Guid>("OrgId")
                        .HasColumnType("uuid")
                        .HasColumnName("org_id");

                    b.Property<decimal?>("CostPerHour")
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("cost_per_hour");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<decimal?>("DailyRate")
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("daily_rate");

                    b.Property<decimal?>("MonthlyRate")
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("monthly_rate");

                    b.Property<string>("PayCadence")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("pay_cadence");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("role");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("UserId", "OrgId");

                    b.HasIndex("OrgId")
                        .HasDatabaseName("ix_org_memberships_org_id");

                    b.ToTable("org_memberships", null, t =>
                        {
                            t.HasCheckConstraint("ck_org_memberships_pay_cadence", "pay_cadence IS NULL OR pay_cadence IN ('hourly','daily','monthly')");
                        });
                });

            modelBuilder.Entity("TimeFlow.Data.Models.Organisation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasDefaultValue("EUR")
                        .HasColumnName("currency");

                    b.Property<string>("HolidayProfileJson")
                        .HasColumnType("text")
                        .HasColumnName("holiday_profile");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("name");

                    b.Property<Guid?>("OwnerId")
                        .HasColumnType("uuid")
                        .HasColumnName("owner_id");

                    b.Property<string>("ScheduleConfigJson")
                        .HasColumnType("text")
                        .HasColumnName("schedule_config");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId");

                    b.ToTable("organisations", (string)null);
                });

            modelBuilder.Entity("TimeFlow.Data.Models.ProjectMember", b =>
                {
                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("project_id");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<DateTime>("AllocatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("allocated_at");

                    b.Property<Guid?>("AllocatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("allocated_by");

                    b.Property<decimal?>("CostPerHour")
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("cost_per_hour");

                    b.Property<bool>("Denied")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("denied");

                    b.Property<Guid>("OrgId")
                        .HasColumnType("uuid")
                        .HasColumnName("org_id");

                    b.Property<string>("RoleOnProject")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasDefaultValue("developer")
                        .HasColumnName("role_on_project");

                    b.HasKey("ProjectId", "UserId");

                    b.HasIndex("AllocatedBy");

                    b.HasIndex("OrgId")
                        .HasDatabaseName("ix_project_members_org");

                    b.HasIndex("UserId", "ProjectId")
                        .HasDatabaseName("ix_project_members_user_project");

                    b.ToTable("project_members", (string)null);
                });

            modelBuilder.Entity("TimeFlow.Data.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)")
                        .HasColumnName("email");

                    b.Property<DateTime?>("EmailVerifiedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("email_verified_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("name");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ix_users_email_unique");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("TimeFlow.Data.Models.UserTwoFactor", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<string>("BackupCodesJson")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("backup_codes");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("EnabledAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("enabled_at");

                    b.Property<string>("Secret")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("secret");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("UserId");

                    b.ToTable("user_two_factor", (string)null);
                });

            modelBuilder.Entity("TimeFlow.Data.Models.Worklog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<decimal>("Hours")
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("hours");

                    b.Property<Guid?>("InvoiceLineId")
                        .HasColumnType("uuid")
                        .HasColumnName("invoice_line_id");

                    b.Property<bool>("IsBillable")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_billable");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<Guid>("OrgId")
                        .HasColumnType("uuid")
                        .HasColumnName("org_id");

                    b.Property<Guid?>("ProjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("project_id");

                    b.Property<string>("PushErrorCode")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("push_error_code");

                    b.Property<string>("PushStatus")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("push_status");

                    b.Property<string>("Source")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("source");

                    b.Property<Guid?>("TaskId")
                        .HasColumnType("uuid")
                        .HasColumnName("task_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpstreamWorklogId")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("upstream_worklog_id");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<DateOnly>("WorkDate")
                        .HasColumnType("date")
                        .HasColumnName("work_date");

                    b.HasKey("Id");

                    b.HasIndex("InvoiceLineId");

                    b.HasIndex("ProjectId");

                    b.HasIndex("PushStatus")
                        .HasDatabaseName("ix_worklogs_push_status");

                    b.HasIndex("TaskId");

                    b.HasIndex("OrgId", "WorkDate")
                        .HasDatabaseName("ix_worklogs_org_date");

                    b.HasIndex("UserId", "WorkDate")
                        .HasDatabaseName("ix_worklogs_user_date");

                    b.ToTable("worklogs", (string)null);
                });

            modelBuilder.Entity("TimeFlow.Data.Models.AuditLog", b =>
                {
                    b.HasOne("TimeFlow.Data.Models.User", null)
                        .WithMany()
                        .HasForeignKey("ActorId")
                        .OnDelete(DeleteBehavior.SetNull);
                });

            modelBuilder.Entity("TimeFlow.Data.Models.IntegrationConnection", b =>
                {
                    b.HasOne("TimeFlow.Data.Models.User", null)
                        .WithMany()
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("TimeFlow.Data.Models.Organisation", "Org")
                        .WithMany()
                        .HasForeignKey("OrgId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TimeFlow.Data.Models.NativeProject", "Project")
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TimeFlow.Data.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Org");

                    b.Navigation("Project");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TimeFlow.Data.Models.IntegrationSyncJob", b =>
                {
                    b.HasOne("TimeFlow.Data.Models.IntegrationConnection", null)
                        .WithMany()
                        .HasForeignKey("ConnectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TimeFlow.Data.Models.User", null)
                        .WithMany()
                        .HasForeignKey("StartedBy")
                        .OnDelete(DeleteBehavior.SetNull);
                });

            modelBuilder.Entity("TimeFlow.Data.Models.Invoice", b =>
                {
                    b.HasOne("TimeFlow.Data.Models.User", null)
                        .WithMany()
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("TimeFlow.Data.Models.Organisation", null)
                        .WithMany()
                        .HasForeignKey("OrgId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TimeFlow.Data.Models.NativeProject", "Project")
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Project");
                });

            modelBuilder.Entity("TimeFlow.Data.Models.InvoiceLine", b =>
                {
                    b.HasOne("TimeFlow.Data.Models.Invoice", "Invoice")
                        .WithMany("Lines")
                        .HasForeignKey("InvoiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TimeFlow.Data.Models.Worklog", null)
                        .WithMany()
                        .HasForeignKey("WorklogId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Invoice");
                });

            modelBuilder.Entity("TimeFlow.Data.Models.NativeProject", b =>
                {
                    b.HasOne("TimeFlow.Data.Models.IntegrationConnection", "Connection")
                        .WithMany()
                        .HasForeignKey("ConnectionId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("TimeFlow.Data.Models.User", null)
                        .WithMany()
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("TimeFlow.Data.Models.Organisation", "Org")
                        .WithMany()
                        .HasForeignKey("OrgId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TimeFlow.Data.Models.NativeProject", "ParentProject")
                        .WithMany()
                        .HasForeignKey("ParentProjectId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Connection");

                    b.Navigation("Org");

                    b.Navigation("ParentProject");
                });

            modelBuilder.Entity("TimeFlow.Data.Models.NativeTask", b =>
                {
                    b.HasOne("TimeFlow.Data.Models.User", null)
                        .WithMany()
                        .HasForeignKey("AssigneeId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("TimeFlow.Data.Models.IntegrationConnection", "Connection")
                        .WithMany()
                        .HasForeignKey("ConnectionId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("TimeFlow.Data.Models.User", null)
                        .WithMany()
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("TimeFlow.Data.Models.NativeProject", "Project")
                        .WithMany("Tasks")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Connection");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("TimeFlow.Data.Models.OrgMembership", b =>
                {
                    b.HasOne("TimeFlow.Data.Models.Organisation", "Org")
                        .WithMany("Memberships")
                        .HasForeignKey("OrgId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TimeFlow.Data.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Org");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TimeFlow.Data.Models.Organisation", b =>
                {
                    b.HasOne("TimeFlow.Data.Models.User", "Owner")
                        .WithMany()
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("TimeFlow.Data.Models.ProjectMember", b =>
                {
                    b.HasOne("TimeFlow.Data.Models.User", null)
                        .WithMany()
                        .HasForeignKey("AllocatedBy")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("TimeFlow.Data.Models.NativeProject", "Project")
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TimeFlow.Data.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TimeFlow.Data.Models.UserTwoFactor", b =>
                {
                    b.HasOne("TimeFlow.Data.Models.User", "User")
                        .WithOne("TwoFactor")
                        .HasForeignKey("TimeFlow.Data.Models.UserTwoFactor", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("TimeFlow.Data.Models.Worklog", b =>
                {
                    b.HasOne("TimeFlow.Data.Models.InvoiceLine", null)
                        .WithMany()
                        .HasForeignKey("InvoiceLineId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("TimeFlow.Data.Models.NativeProject", null)
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("TimeFlow.Data.Models.NativeTask", null)
                        .WithMany()
                        .HasForeignKey("TaskId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("TimeFlow.Data.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TimeFlow.Data.Models.Invoice", b =>
                {
                    b.Navigation("Lines");
                });

            modelBuilder.Entity("TimeFlow.Data.Models.NativeProject", b =>
                {
                    b.Navigation("Tasks");
                });

            modelBuilder.Entity("TimeFlow.Data.Models.Organisation", b =>
                {
                    b.Navigation("Memberships");
                });

            modelBuilder.Entity("TimeFlow.Data.Models.User", b =>
                {
                    b.Navigation("TwoFactor");
                });
#pragma warning restore 612, 618
        }
    }
}
